format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_intf_parallel_smc}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DataCommandSelectControl}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Peripheral}
  - type: Combo
    attributes: {id: ReadStrobeControl}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Peripheral}
  - type: Combo
    attributes: {id: WriteStrobeControl}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Peripheral}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: SMC_CS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: smc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: smc_cs0}
  - type: DirectCapability
    attributes: {id: le_gfx_intf_parallel_smc}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_external}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: Parallel Display Interface}
- type: ElementPosition
  attributes: {x: '220', y: '106', id: le_gfx_intf_parallel_smc}
