configName: lcc_rgb565_mxt_e70_IAR
folderName: legato_qs_e70_xu_tm4301b.IAR
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME70Q21B
projectName: legato_qs_e70_xu_tm4301b.IAR
settings:
  PackageFilter: aerospace;audio;bsp;core;csp;gfx;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.3.73\same70b\atdf\ATSAME70Q21B.atdf
