configName: ssd1963_rgb565_mxt_e70
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME70Q21B
projectName: ''
settings:
  PackageFilter: aerospace;audio;bsp;core;csp;gfx;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.3.73\same70b\atdf\ATSAME70Q21B.atdf
