format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_driver_lcc}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DMAChannel}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '1'}
  - type: Boolean
    attributes: {id: DMAChannelSelected}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: 'true'}
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '272'}
  - type: Integer
    attributes: {id: DisplayHorzBackPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '2'}
  - type: Integer
    attributes: {id: DisplayHorzFrontPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '2'}
  - type: Integer
    attributes: {id: DisplayHorzPulseWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '41'}
  - type: Menu
    attributes: {id: DisplaySettingsMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: DisplayVertBackPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '2'}
  - type: Integer
    attributes: {id: DisplayVertFrontPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '2'}
  - type: Integer
    attributes: {id: DisplayVertPulseWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '10'}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '480'}
  - type: Integer
    attributes: {id: EBIChipSelectIndex}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '0'}
  - type: Comment
    attributes: {id: HALComment}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: OldDMAChannel}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '1'}
  - type: Combo
    attributes: {id: PeripheralControl}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: TC}
  - type: Integer
    attributes: {id: TCChannel}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: '1'}
  - type: Combo
    attributes: {id: TCChannelCompare}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: B}
  - type: Integer
    attributes: {id: TCInstance}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '2'}
  - type: Menu
    attributes: {id: TCPeripheralSettings}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: Graphics Display}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_disp_pdatm4301b_480x272}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_display}
  - type: DirectDependency
    attributes: {id: SMC_CS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: smc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: smc_cs0}
  - type: DirectDependency
    attributes: {id: TMR}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: tc2}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: TC2_TMR}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: DirectCapability
    attributes: {id: gfx_driver_lcc}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_legato}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_driver}
- type: ElementPosition
  attributes: {x: '603', y: '203', id: le_gfx_driver_lcc}
