format_version: v1.0
type: UniqueComponent
attributes: {id: tc2}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ENCODER_POS_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: TC2_QuadraturePositionGet}
  - type: String
    attributes: {id: ENCODER_POS_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: ''}
  - type: String
    attributes: {id: ENCODER_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: TC2_QuadratureStart}
  - type: String
    attributes: {id: ENCODER_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: TC2_QuadratureStop}
  - type: Integer
    attributes: {id: TC1_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '150000000'}
  - type: Menu
    attributes: {id: TC1_COMPARE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TC1_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: 'true'}
  - type: Combo
    attributes: {id: TC1_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: COMPARE}
  - type: Comment
    attributes: {id: TC1_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Clock resolution is 6.66666666667 nS****'}
  - type: Menu
    attributes: {id: TC1_TIMER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: TC1_TIMER_PERIOD_CMT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Period Count is 60000****'}
  - type: Long
    attributes: {id: TC1_TIMER_PERIOD_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '60000'}
  - type: Integer
    attributes: {id: TC3_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '150000000'}
  - type: Boolean
    attributes: {id: TC3_PCK7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: 'false'}
  - type: Comment
    attributes: {id: TC_QEI_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Time Base is 100.1 uS****'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: TC2_TMR}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_lcc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: TMR}
- type: ElementPosition
  attributes: {x: '460', y: '339', id: tc2}
